'use strict';

/**
 * #399 -- reported that exportPackage aliased the store's live content/
 *         metadata/provenance into the exported package. That does NOT hold:
 *         exportPackage ends with `package: deepClone(pkg)`, so the caller
 *         never receives a live reference. The aliasing is confined to a local
 *         that never escapes. The tests below pin that caller-visible contract
 *         so it cannot regress if that final clone is ever removed. The one
 *         real defect in #399 -- the no-op `strength` ternary -- is fixed.
 *
 * #400 -- importPackage's strict-mode conflict check ran *after* the
 *         transaction committed, so it reported "import failed" over a
 *         database that already held the package's non-conflicting records.
 *         It was in fact unreachable: conflicts were only recorded under
 *         'idempotent', so strict mode silently overwrote instead.
 */

const test = require('node:test');
const assert = require('node:assert/strict');

const MemoryStore = require('../lib/memory-store');

function seededStore(workspaceId = 'ws') {
  const store = new MemoryStore();
  const result = store.store({
    content: { text: 'hello', tags: ['a', 'b'] },
    workspaceId,
    metadata: { note: 'original', nested: { deep: 1 } },
  });
  assert.equal(result.ok, true, 'seed memory was stored');
  return { store, memoryId: result.memory.memoryId };
}

// ─── #399: caller-visible isolation contract (already held; now pinned) ────

test('#399: mutating an exported package does not corrupt the store', () => {
  const { store } = seededStore();

  const exported = store.exportPackage({ workspaceId: 'ws' });
  assert.equal(exported.ok, true);
  const pkg = exported.package;
  assert.equal(pkg.memories.length, 1);

  // Provenance is generated by the store, so capture it before tampering
  // rather than assuming a literal.
  const originalSourceRef = pkg.memories[0].provenance
    ? pkg.memories[0].provenance.sourceRef
    : null;

  // A caller doing ordinary things with its own copy of the export.
  pkg.memories[0].content.text = 'TAMPERED';
  pkg.memories[0].content.tags.push('injected');
  pkg.memories[0].metadata.note = 'TAMPERED';
  pkg.memories[0].metadata.nested.deep = 999;
  if (pkg.memories[0].provenance) pkg.memories[0].provenance.sourceRef = 'TAMPERED';

  const fresh = store.exportPackage({ workspaceId: 'ws' }).package.memories[0];
  assert.equal(fresh.content.text, 'hello', 'store content is untouched');
  assert.deepEqual(fresh.content.tags, ['a', 'b'], 'store content arrays are untouched');
  assert.equal(fresh.metadata.note, 'original', 'store metadata is untouched');
  assert.equal(fresh.metadata.nested.deep, 1, 'nested store metadata is untouched');
  if (originalSourceRef !== null) {
    assert.equal(fresh.provenance.sourceRef, originalSourceRef, 'store provenance is untouched');
  }
});

test('#399: two exports do not share object identity', () => {
  const { store } = seededStore();

  const a = store.exportPackage({ workspaceId: 'ws' }).package.memories[0];
  const b = store.exportPackage({ workspaceId: 'ws' }).package.memories[0];

  assert.deepEqual(a.content, b.content, 'exports are value-equal');
  assert.notEqual(a.content, b.content, 'but not the same object');
  assert.notEqual(a.metadata, b.metadata);
});

test('#399: exported shape is unchanged (undefined stays undefined)', () => {
  const store = new MemoryStore();
  store.store({ content: { text: 'plain' }, workspaceId: 'ws' });

  const memory = store.exportPackage({ workspaceId: 'ws' }).package.memories[0];
  assert.ok(Object.prototype.hasOwnProperty.call(memory, 'metadata'));
  assert.deepEqual(memory.content, { text: 'plain' });
});

// ─── #400: strict mode must roll back, not commit-then-complain ─────────────

function conflictingPackage(store, memoryId) {
  const pkg = store.exportPackage({ workspaceId: 'ws' }).package;
  // One record that collides with an existing id but has different content...
  pkg.memories[0].content = { text: 'different content entirely' };
  // ...plus one clean record that would import fine on its own.
  pkg.memories.push({
    ...pkg.memories[0],
    memoryId: `${memoryId}-clean`,
    content: { text: 'clean record' },
  });
  return pkg;
}

test('#400: strict mode rolls back — nothing from the package is committed', () => {
  const { store, memoryId } = seededStore();
  const pkg = conflictingPackage(store, memoryId);

  const before = store.exportPackage({ workspaceId: 'ws' }).package.memories.length;

  const result = store.importPackage(pkg, { targetWorkspaceId: 'ws', mode: 'strict' });

  assert.equal(result.ok, false, 'strict import reports failure');
  assert.equal(result.error.code, 'CONFLICT');
  assert.ok(Array.isArray(result.error.details) && result.error.details.length > 0);

  const after = store.exportPackage({ workspaceId: 'ws' }).package.memories;
  assert.equal(after.length, before, 'no records were added by a failed strict import');
  assert.equal(
    after.some((m) => m.memoryId === `${memoryId}-clean`),
    false,
    'the clean record from the same package was rolled back too',
  );
  // The original record must survive untouched -- strict mode used to
  // silently overwrite it.
  const original = after.find((m) => m.memoryId === memoryId);
  assert.equal(original.content.text, 'hello', 'the conflicting record was not overwritten');
});

test('#400: strict mode succeeds when there is no conflict', () => {
  const { store } = seededStore();
  const pkg = store.exportPackage({ workspaceId: 'ws' }).package;

  const target = new MemoryStore();
  const result = target.importPackage(pkg, { targetWorkspaceId: 'ws', mode: 'strict' });

  assert.equal(result.ok, true, 'a clean strict import still succeeds');
  assert.equal(result.imported.memories, 1);
});

test('#400: idempotent mode still skips conflicts and keeps the clean records', () => {
  const { store, memoryId } = seededStore();
  const pkg = conflictingPackage(store, memoryId);

  const result = store.importPackage(pkg, { targetWorkspaceId: 'ws', mode: 'idempotent' });

  assert.equal(result.ok, true, 'idempotent mode does not fail the whole import');
  assert.ok(result.conflicts && result.conflicts.length > 0, 'conflicts are still reported');

  const after = store.exportPackage({ workspaceId: 'ws' }).package.memories;
  assert.equal(
    after.some((m) => m.memoryId === `${memoryId}-clean`),
    true,
    'the clean record was imported',
  );
  const original = after.find((m) => m.memoryId === memoryId);
  assert.equal(original.content.text, 'hello', 'the conflicting record was left alone');
});

test('#400: a re-import of an unchanged package is a no-op in both modes', () => {
  const { store } = seededStore();
  const pkg = store.exportPackage({ workspaceId: 'ws' }).package;

  for (const mode of ['idempotent', 'strict']) {
    const result = store.importPackage(pkg, { targetWorkspaceId: 'ws', mode });
    assert.equal(result.ok, true, `${mode}: identical content is not a conflict`);
    assert.equal(result.imported.memories, 0, `${mode}: nothing new imported`);
  }
});
