apiVersion: v1
kind: Service
metadata:
  name: huqan
  namespace: huqan
  labels:
    app.kubernetes.io/name: huqan
    app.kubernetes.io/component: runtime
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: huqan
    app.kubernetes.io/component: runtime
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
