import os
import sys
import json
import subprocess
import glob
import re

# State file to track which files have been analyzed, stored in repo or workflow cache
STATE_FILE = os.environ.get("STATE_FILE_PATH", ".huqan_automation_state.json")
REPO_DIR = os.environ.get("GITHUB_WORKSPACE", ".")

def get_state():
    if os.path.exists(STATE_FILE):
        with open(STATE_FILE, 'r') as f:
            return json.load(f)
    return {"analyzed_files": [], "pending_files": []}

def save_state(state):
    with open(STATE_FILE, 'w') as f:
        json.dump(state, f, indent=2)

def initialize_file_list():
    """Find all JS files in core directories to analyze"""
    state = get_state()
    if not state["pending_files"] and not state["analyzed_files"]:
        # Find files in lib/ and root
        files = []
        for ext in ["*.js"]:
            files.extend(glob.glob(os.path.join(REPO_DIR, ext)))
            files.extend(glob.glob(os.path.join(REPO_DIR, "lib", ext)))
            
        # Filter out test files to focus on architecture first
        core_files = [f for f in files if not f.endswith(".test.js")]
        
        # Sort for deterministic order, prioritizing core files
        core_files.sort()
        
        # Make paths relative to repo root
        state["pending_files"] = [os.path.relpath(f, REPO_DIR) for f in core_files]
        save_state(state)
    return state

def analyze_file(file_path, content):
    """Use rule-based regex to analyze the file content for architectural issues"""
    issues = []
    
    # Check 1: Hardcoded secrets or logging secrets
    if re.search(r'console\.(log|error|warn)\(.*(password|secret|token|key|credential).*\)', content, re.IGNORECASE):
        issues.append("- **Potential Secret Leak**: Logging statements appear to include sensitive keywords (password, secret, token, etc.). Check for PII or secret leakage to logs.")
        
    # Check 2: Core files shouldn't have too much business logic (simple size check)
    core_files = ['kernel.js', 'kernel.v2.js', 'graph.js', 'server.js', 'cli.js', 'mcpServer.js']
    base_name = os.path.basename(file_path)
    if base_name in core_files and len(content.splitlines()) > 2000:
        issues.append(f"- **Core File Bloat**: {base_name} is very large (>2000 lines). Ensure new domain/business logic is delegated to smaller modules rather than added directly to core validation files.")
        
    # Check 3: Fail-closed semantics (catching errors without re-throwing or returning error state)
    if re.search(r'catch\s*\([^)]*\)\s*\{\s*(console\.[a-z]+\([^)]+\);?)?\s*\}', content):
        issues.append("- **Fail-Closed Violation**: Found empty catch blocks or catch blocks that only log. HUQAN requires strict fail-closed semantics; errors must be handled, escalated, or cause a safe failure state.")
        
    # Check 4: Bypass admission/approval (writing to DB without checking approval)
    if re.search(r'(db|store)\.(run|exec|insert|update)\(', content) and not re.search(r'(gate|admission|approve|policy|risk)', content, re.IGNORECASE):
        issues.append("- **Admission Bypass Risk**: Found database mutation calls but didn't find clear references to admission, approval, or policy gates in the same file. Ensure all writes pass through the Trust Receipt/Approval boundaries.")

    if not issues:
        return "NO_ISSUES_FOUND"
        
    report = f"### Architectural & Security Review Findings for `{file_path}`\n\n"
    report += "During automated static analysis, the following potential architectural or security issues were flagged:\n\n"
    report += "\n".join(issues)
    report += "\n\n*This is an automated report generated by the HUQAN hourly analyzer script. Please review and close if these are false positives.*"
    
    return report

def open_github_issue(file_path, issue_body):
    """Open an issue on GitHub using gh CLI"""
    title = f"Architecture/Security Review: Potential issues in {file_path}"
    
    # Write body to a temporary file for gh CLI
    temp_body_file = "/tmp/issue_body.md"
    with open(temp_body_file, "w") as f:
        f.write(issue_body)
        
    try:
        # Check if gh CLI is available
        subprocess.run(["gh", "--version"], check=True, capture_output=True)
        
        # Create issue in the repository
        cmd = f"gh issue create --title '{title}' --body-file {temp_body_file}"
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        
        if result.returncode == 0:
            print(f"Successfully opened issue for {file_path}: {result.stdout.strip()}")
            return True
        else:
            print(f"Failed to open issue for {file_path}: {result.stderr}")
            return False
    except FileNotFoundError:
        print(f"GitHub CLI (gh) not found. Would have opened issue for {file_path}:\n\n{issue_body}")
        return True # Return true to continue the loop in testing environments
    except Exception as e:
        print(f"Error opening issue: {e}")
        return False
    finally:
        if os.path.exists(temp_body_file):
            os.remove(temp_body_file)

def main():
    print("Starting HUQAN hourly file analyzer...")
    
    # Check if repo exists
    if not os.path.exists(REPO_DIR):
        print(f"Error: Repository not found at {REPO_DIR}")
        sys.exit(1)
        
    state = initialize_file_list()
    
    if not state["pending_files"]:
        print("All files have been analyzed! Resetting list...")
        state["pending_files"] = state["analyzed_files"]
        state["analyzed_files"] = []
        save_state(state)
    
    # Get the next file to analyze
    target_file = state["pending_files"].pop(0)
    full_path = os.path.join(REPO_DIR, target_file)
    
    print(f"Analyzing {target_file}...")
    
    try:
        with open(full_path, 'r') as f:
            content = f.read()
            
        analysis_result = analyze_file(target_file, content)
        
        if analysis_result != "NO_ISSUES_FOUND":
            print(f"Issues found in {target_file}. Opening GitHub issue...")
            success = open_github_issue(target_file, analysis_result)
            if not success:
                # If issue creation failed, put the file back in pending
                state["pending_files"].insert(0, target_file)
                save_state(state)
                sys.exit(1)
        else:
            print(f"No issues found in {target_file}.")
            
        # Mark as analyzed
        state["analyzed_files"].append(target_file)
        save_state(state)
        print("Analysis complete.")
        
    except Exception as e:
        print(f"Error analyzing {target_file}: {str(e)}")
        # Put file back on error
        state["pending_files"].insert(0, target_file)
        save_state(state)
        sys.exit(1)

if __name__ == "__main__":
    main()
