'use strict';

/**
 * HUQAN adapter for a custom agent. Generated by `huqan-gate adapter`.
 *
 * Call `huqanCheck()` immediately before your agent executes a tool call, and
 * let it throw. It builds the huqan.external-action.v1 envelope, runs the gate,
 * and refuses anything that is not an explicit `allow`.
 *
 * It fails CLOSED on purpose. If the gate cannot be started, its output cannot
 * be parsed, or it answers with a schema this adapter does not know, the action
 * does not run. An adapter that swallowed those cases would look like
 * enforcement while allowing everything the gate could not answer.
 *
 * The gate command below was proven at generation time: it was run against a
 * denylisted command and had to answer `block` with DENYLISTED_COMMAND_BLOCKED
 * before being written here. Override it with the HUQAN_GATE_PATH environment
 * variable if the path moves.
 */

const { spawnSync } = require('node:child_process');
const { existsSync } = require('node:fs');

const GATE_COMMAND = '__HUQAN_GATE_COMMAND__';
const ENVELOPE_SCHEMA = 'huqan.external-action.v1';
const DECISION_SCHEMA = 'huqan.guard-decision.v1';
const TIMEOUT_MS = 30000;

class HuqanBlocked extends Error {
  constructor(decision, reason, receiptId) {
    super(`HUQAN ${decision}: ${reason}`);
    this.name = 'HuqanBlocked';
    this.decision = decision;
    this.reason = reason;
    this.receiptId = receiptId || null;
  }
}

function gateInvocation() {
  const override = String(process.env.HUQAN_GATE_PATH || '').trim();
  // An override that names a real file is used whole. Splitting it on spaces
  // would break the common case on Windows -- a shim under `C:\Program
  // Files\...` -- and the breakage is silent, because a gate that cannot start
  // fails closed and simply refuses everything.
  if (override && existsSync(override)) return [override];
  return (override || GATE_COMMAND).split(' ').filter(Boolean);
}

/**
 * @param {object} call
 * @param {string} call.toolName    your agent's name for the tool
 * @param {string} [call.kind]      'shell' | 'file' | 'network' | ...
 * @param {object} call.args        the tool arguments, e.g. { command: 'npm test' }
 * @param {string} [call.cwd]
 * @param {string} [call.workspaceRoot]
 * @param {string} [call.workspaceId]
 * @param {string} [call.agentName]
 * @param {string} [call.sessionId]
 * @param {string} [call.turnId]
 * @param {string} [call.invocationId]
 * @returns {{decision: 'allow', reason: string, receiptId: string|null}}
 * @throws {HuqanBlocked} on anything that is not an explicit allow
 */
function huqanCheck(call = {}) {
  const cwd = call.cwd || process.cwd();
  const envelope = {
    schemaVersion: ENVELOPE_SCHEMA,
    invocationId: call.invocationId || `call-${Date.now()}-${Math.random().toString(16).slice(2)}`,
    agentName: call.agentName || 'my-agent',
    agentVersion: call.agentVersion || '',
    sessionId: call.sessionId || 'session-1',
    turnId: call.turnId || '',
    toolName: call.toolName,
    kind: call.kind || 'shell',
    args: call.args || {},
    cwd,
    workspaceRoot: call.workspaceRoot || cwd,
    workspaceId: call.workspaceId || 'default',
  };

  const argv = gateInvocation();
  const run = spawnSync(argv[0], [...argv.slice(1), '--profile', 'generic'], {
    input: JSON.stringify(envelope),
    encoding: 'utf8',
    timeout: TIMEOUT_MS,
  });

  // Unreachable gate is a refusal, never a pass.
  if (run.error) throw new HuqanBlocked('block', `gate could not be started: ${run.error.message}`);

  let decision;
  try {
    decision = JSON.parse(run.stdout || '');
  } catch (_) {
    throw new HuqanBlocked('block', `gate output could not be parsed: ${String(run.stdout || run.stderr || '').slice(0, 200)}`);
  }

  // A response this adapter does not understand is not an allow. A future gate
  // that changes the contract must stop this adapter, not slip past it.
  if (decision.schemaVersion !== DECISION_SCHEMA) {
    throw new HuqanBlocked('block', `unexpected decision schema: ${decision.schemaVersion}`);
  }
  if (decision.decision !== 'allow') {
    throw new HuqanBlocked(decision.decision || 'block', decision.reason || 'no reason given', decision.receiptId);
  }

  return { decision: 'allow', reason: decision.reason || '', receiptId: decision.receiptId || null };
}

module.exports = { huqanCheck, HuqanBlocked, GATE_COMMAND, DECISION_SCHEMA, ENVELOPE_SCHEMA };
