'use strict';

const { layerOf, sharedOf } = require('./check-layers');

const ENTRYPOINT = new Set([
  'cli.js', 'server.js', 'mcpServer.js', 'index.js', 'agentRuntime.js',
]);
const ORDER = ['entrypoint', 'domain', 'storage', 'shared'];

const isEntrypoint = (file) => ENTRYPOINT.has(file)
  || file.startsWith('bin/')
  || file.startsWith('scripts/')
  || file.startsWith('examples/');

function renderMermaid(graph) {
  const shared = sharedOf(graph, isEntrypoint);
  const edgeCounts = new Map();

  for (const [from, deps] of graph) {
    const fromLayer = layerOf(from, shared);
    for (const to of new Set(deps)) {
      const toLayer = layerOf(to, shared);
      if (fromLayer === toLayer) continue;
      const key = `${fromLayer}->${toLayer}`;
      edgeCounts.set(key, (edgeCounts.get(key) || 0) + 1);
    }
  }

  const lines = [
    '```mermaid',
    'flowchart TB',
    '  entrypoint["entrypoint"]',
    '  domain["domain"]',
    '  storage["storage"]',
    '  shared["shared"]',
  ];
  for (const from of ORDER) {
    for (const to of ORDER) {
      if (from === to) continue;
      const count = edgeCounts.get(`${from}->${to}`) || 0;
      if (count > 0) lines.push(`  ${from} -->|"${count}"| ${to}`);
    }
  }
  lines.push('```');
  lines.push('');
  lines.push('_Generated by `node scripts/architecture-snapshot.js --mermaid` (#2641)._');
  return lines.join('\n');
}

module.exports = { renderMermaid };
